### ISSUE TITLE
1.10 Mark of the falling tower not working

### ISSUE THREAD

**Issue by Quezler** [WayofTime/BloodMagic#1067]
#### Issue Description:
Mark of the falling tower not working

#### What happens:

Meteor does not spawn

#### What you expected to happen:

Meteor being spawned

#### Steps to reproduce:

1. build complete ritual
2. try to activate it
3. nothing happens after 'a rush of energy flows through the ritual!' (dropping a gold/iron/diamond block changes nothing)
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.9.4-2.1.0-69
- Minecraft: 1.10
- Forge: unsure

**Comment by TehNut** [comment]
Working just fine for me. 

![](http://i.imgur.com/ptI7r5q.png)

You are also very outdated.

**Comment by Boolyman** [comment]
I have seen a lot of people fail to summon the meteor because they are placing blocks in the air above the altar in order to halt the meteor before slamming into the altar.  While this does work, if you place the blocks too high, it will interfere with the spawning of the meteor, and prevent the ritual from starting.   Though I am not promoting trying to cheese out of the destruction... If you are going to try to avoid it,                                                                                                                                                                                      use only one strong block like obsidian, placed about 15 blocks directly above the Master Ritual Stone... no more than that.

**Comment by tommypoints** [comment]
Don't forget to throw the catalyst on the master ritual stone after activating it.
