### ISSUE TITLE
Ritual diviner: double message

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1129]
![blood magic double ritual diviner message](https://cloud.githubusercontent.com/assets/25916106/25065864/5e743d28-2217-11e7-8208-f343dff0737a.png)

Perhaps the chat message should be disabled?

****

**Minecraft version**: 1.10.2
**Minecraft Forge version**: 12.18.3.2185
**Blood Magic version**: 2.1.9-78

**Comment by Arcaratus** [comment]
This is also an intended feature. (Close)

**Comment by ghost** [comment]
@Arcaratus Why would it be intended to tell the player which ritual is selected twice simultaneously?

That doesn’t make much sense.

**Comment by TehNut** [comment]
Showing both is most definitely not intended.

Also, please stop ignoring the template. I will start closing your issues if you don't.

**Comment by PapiDimmi** [comment]
@TehNut The template is unnecessary. Rather than showing a screenshot of my issue, describing my issue, and saying what versions I’m using, like I usually do, I have to answer questions that, most of the time, are totally irrelevant. This forces me to repeat myself and include sentences that don’t add to the issue and are a waste of time.

I always write what Minecraft, Forge, and Blood Magic versions I use.

Short version: The template is useless. If I have an issue, I’ll describe the issue and provide all the necessary details.

_E.g._, let’s say that I included the “steps to reproduce” in this issue. It’d go like this:

1. Craft a ritual diviner.
2. Equip the ritual diviner.
3. Shift + right-click to change the selected ritual.
4. Read the chat and the message about your hotbar.

Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

This is _extremely_ obvious and thus a complete waste of time to both write and read.

Closing issues because I didn’t use an irrelevant template means that you’d be completely ignoring bugs, suggestions, and other types of issues in your mod, just because of something that doesn’t even matter.

**Comment by ghost** [comment]
@TehNut The template is unnecessary. Rather than showing a screenshot of my issue, describing my issue, and saying what versions I’m using, like I usually do, I have to answer questions that, most of the time, are totally irrelevant. This forces me to repeat myself and include sentences that don’t add to the issue and are a waste of time.

I always write what Minecraft, Forge, and Blood Magic versions I use.

Short version: The template is useless. If I have an issue, I’ll describe the issue and provide all the necessary details.

_E.g._, let’s say that I included the “steps to reproduce” in this issue. It’d go like this:

1. Craft a ritual diviner.
2. Equip the ritual diviner.
3. Shift + right-click to change the selected ritual.
4. Read the chat and the message about your hotbar.

Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

This is _extremely_ obvious and thus a complete waste of time to both write and read.

Closing issues because I didn’t use an irrelevant template means that you’d be completely ignoring bugs, suggestions, and other types of issues in your mod, just because of something that doesn’t even matter.

Wouldn’t you much rather have a nicely formatted issue with all the details you need than a long issue with unnecessary sections that include irrelevant information?

**Comment by WayofTime** [comment]
It frankly DOES matter. There have been SOOOOOOOOO many times that people have ignored adding basic information, such as version information etc, that it makes me take a deep breath before openning up an issue.

It makes it a lot easier for us, who have to go through these issues daily.

**Comment by ghost** [comment]
I described my issue, included a screenshot, and included the version of Minecraft, Blood Magic, and Forge.

What more do you honestly need?

**Comment by WayofTime** [comment]
As far as the issue is concerned, the first message shown is just what happens when the name of an item changes initially. This goes away when you click enough times, and therefore the message in chat (which does not spam in any way) is necessary.

**Comment by ghost** [comment]
Damn, I totally forgot about that vanilla mechanic. I guess I’m becoming direwolf20 now.

I didn’t know that the name of the item changed depending on which ritual is active.

My bad.

**Comment by TehNut** [comment]
>Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

If you're playing a modpack, ***all*** reports should go to the pack dev first. No exceptions. In a perfect world, the only people who would report issues to mod authors are the pack devs and players using custom packs.

>This is extremely obvious and thus a complete waste of time to both write and read.

I don't care. Do it anyway. 

>Closing issues because I didn’t use an irrelevant template means that you’d be completely ignoring bugs, suggestions, and other types of issues in your mod, just because of something that doesn’t even matter.

I'm not going to sift through your custom format to find the information I need. It's not worth my time. Fill out the template.

>Wouldn’t you much rather have a nicely formatted issue with all the details you need than a long issue with unnecessary sections that include irrelevant information?

No, I'd rather have you fill out the template that *I* chose for people to fill out.

**Comment by PapiDimmi** [comment]
>>Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

>If you're playing a modpack, all reports should go to the pack dev first. No exceptions. In a perfect world, the only people who would report issues to mod authors are the pack devs and players using custom packs.

Then the cycle would go like this:

Report to modpack author → Modpack author asks you to report to the mod developers → Mod devs tell you to report to the modpack author.

If a mod has a bug, why would it be caused by the modpack? Modpack authors don’t code mods. I have no idea how a modpack author can… create a bug in a mod.

>>This is extremely obvious and thus a complete waste of time to both write and read.

**Comment by PapiDimmi** [comment]
>>Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

>If you're playing a modpack, all reports should go to the pack dev first. No exceptions. In a perfect world, the only people who would report issues to mod authors are the pack devs and players using custom packs.

Then the cycle would go like this:

Report to modpack author → Modpack author asks you to report to the mod developers → Mod devs tell you to report to the modpack author.

If a mod has a bug, why would it be caused by the modpack? Modpack authors don’t code mods. I have no idea how a modpack author can… create a bug in a mod.

>>This is extremely obvious and thus a complete waste of time to both write and read.

>I don't care. Do it anyway.

Why do you want to waste everyone’s time? The template is nice for people who have no idea what kind of information to put in their issues, but if I provide all the unnecessary information, why should I use a pointless template?

>>Closing issues because I didn’t use an irrelevant template means that you’d be completely ignoring bugs, suggestions, and other types of issues in your mod, just because of something that doesn’t even matter.

>I'm not going to sift through your custom format to find the information I need. It's not worth my time. Fill out the template.

I almost hope that you’re trolling. You can’t be serious. How is a screenshot, a short paragraph describing the issue, and the versions at the bottom a “format” that’s hard to navigate? You perplex me.

**Comment by ghost** [comment]
>>Also, the part asking whether this happens in a modpack is also unnecessary. It’s also misleading, as some people might think that a bug or another type of issue is caused by the modpack, even though it’s the mod’s fault, as in this case.

>If you're playing a modpack, all reports should go to the pack dev first. No exceptions. In a perfect world, the only people who would report issues to mod authors are the pack devs and players using custom packs.

Then the cycle would go like this:

Report to modpack author → Modpack author asks you to report to the mod developers → Mod devs tell you to report to the modpack author.

If a mod has a bug, why would it be caused by the modpack? Modpack authors don’t code mods. I have no idea how a modpack author can… _create_ a bug in a mod.

>>This is extremely obvious and thus a complete waste of time to both write and read.

>I don't care. Do it anyway.

Why do you want to waste everyone’s time? The template is nice for people who have no idea what kind of information to put in their issues, but if I provide all the unnecessary information, why should I use a pointless template?

>>Closing issues because I didn’t use an irrelevant template means that you’d be completely ignoring bugs, suggestions, and other types of issues in your mod, just because of something that doesn’t even matter.

>I'm not going to sift through your custom format to find the information I need. It's not worth my time. Fill out the template.

I almost hope that you’re trolling. You can’t be serious. How is a screenshot, a short paragraph describing the issue, and the versions at the bottom a “format” that’s hard to navigate? You perplex me.

I include all the information that’s necessary, rather than having ten sections with forced information that’s completely irrelevant. You should be thankful for the fact that I don’t want to waste your time.

**Comment by TehNut** [comment]
Like I said, in a perfect world, the modpack devs would be the ones to report. They should do it themselves.

I don't care if you think the template is useless. Use it. Period. End of discussion.

I'm not trolling. Fill out the damn template.
