### ISSUE TITLE
Lava Crystal Consumed (1.11)

### ISSUE THREAD

**Issue by BaronMalkar** [WayofTime/BloodMagic#1180]
#### Issue Description:
Lava Crystal gets consumed as a 200 tick fuel source while using BloodMagic-1.11-2.1.11-80

#### What you expected to happen:
Lava Crystal should persist between smelting operations.

#### Steps to reproduce:

1. Insert Lava Crystal into furnace
2. ???
3. Don't profit

#### Possible solution
I am pretty sure it will work if you change line 37 of ItemLavaCrystal.java from
copiedStack.setCount(1);
to
copiedStack.stackSize = 1;
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.11-80
- Minecraft: 1.11.2
- Forge: 13.20.1.2393

**Comment by TehNut** [comment]
Your solution is literally the exact same thing and also not possible in 1.11. 

I am almost certain I have seen people use the lava crystal just fine. Can you reproduce this with just Blood Magic?

**Comment by BaronMalkar** [comment]
I was able to reproduce with only Blood Magic, Forge, and Guide-API in a pack I just threw together on the twitch launcher. I even tried updating forge to 13.20.1.2425 in case it was forge somehow.

**Comment by talonos2** [comment]
I am having the same issue in my pack. (Also 1.11.2)

@BaronMalkar: Could you give me your mod list, and we can compare them to narrow down what sorts of cross-mod interactions might be causing it?

I'm trying to think of what mods I have that might be affecting vanilla furnace behavior, and not coming up with any. But I *have* to imagine it's some sort of cross-mod conflict, because if this happened solely with Vanilla+Blood Magic, you'd think one of the devs would have noticed by now.

**Comment by talonos2** [comment]
NVM, I just noticed that you said it was an issue even with only Blood Magic, Forge, and Guide API. Strange indeed.

**Comment by kragnoth** [comment]
You do have blood in your blood network, right?  And are you on server or single player client?

**Comment by BaronMalkar** [comment]
Yep have plenty of blood, though even if I didn't the crystal shouldn't be consumed.

**Comment by TehNut** [comment]
This is fixed by 441e7b8952e4f84bb0a99814904cc3ef55583c66 for 1.12.
