### ISSUE TITLE
Request/Suggestion: Enable Void Sigil to remove Fluids from Tanks/Fluid Containers

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1339]
## Issue Description:
Got Water in a Machine. Couldn't remove it.
Pumped it into a Blood Tank. Now the Blood tank is unusable.

## Suggestion:
Allow the Void Sigil to remove fluids from fluid containers. Preferably reducing to the next full bucket (or by one bucket if it's at a full bucket).
Makes it consistent with Water/Lava Sigil which can add to fluid containers.

**Comment by cn-ml** [comment]
I'm playing Blood Magic version 1.12.2-2.2.12-97 in the modpack FTBRevelation 2.2.0-1.12.2.
I just tested this and it seems to be working for me. I tested the void sigil on Thermal Expansions Portable Tank. Maybe you should specify the Bug for the Blood Tank, because for most Forge Fluid containers this already works.

**Comment by keraldi** [comment]
🤔 I actually thought that it was intended behavior to not work.

I'll make a formal bug/issue report, then.

Edit: care to elaborate with which forge fluid containers you tested?
