### ISSUE TITLE
[1.12.2] Crack of the Fractured Crystal Not Working

### ISSUE THREAD

**Issue by Lice2** [WayofTime/BloodMagic#1357]
#### Issue Description:
Note: The Ritual Crack of the Fractured Crystal in Minecraft Version 1.12.2 does not work.

#### What happens:
The Ritual Crack of the Fractured Crystal does not work in Minecraft Version 1.12.2
See video
https://www.youtube.com/watch?v=Dl0prQDbgww

#### What you expected to happen:
That it breaks down the crystals

#### Steps to reproduce:

1. The Ritual Crack of the Fractured Crystal built
2. The Ritual Crack of the Fractured Crystal activates with the Weak Activation Crystal
3. but nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2611-universal

**Comment by keraldi** [comment]
Link sends me to my youtube video folder. Please fix it.

**Comment by wamc2017** [comment]
Edit: Referenced the wrong entry here...

The correct link is https://www.youtube.com/watch?v=Dl0prQDbgww

**Comment by keraldi** [comment]
Ritual area cannot be defined yet. Area of the Crack of the Fractured Crystal is above the MRS. Please fix your names. The Ritual you're using in the video is Crack of the Fractured Crystal, the guidebook entry is Resonance of the Faceted Crystal.

**Comment by wamc2017** [comment]
Sorry, referenced the wrong entry, I'm not the one with the problem..,

**Comment by keraldi** [comment]
I just tested it in SSP, 1.12.2-2.2.12-97 w/ Forge 2655. Both Rituals work. Make sure they're within the confinements of the Ritual and above the MRS.

**Comment by Lice2** [comment]
https://www.youtube.com/watch?v=oUnfNZ0Z8vg
 Resonance of the Faceted Crystal Dont Work

**Comment by wamc2017** [comment]
The crystal cluster needs to be two blocks above the MRS and needs to be grown to full size before it starts to split...

**Comment by keraldi** [comment]
You made the effort of creating an account here specifically to report your problem. Please make the same effort reading the mod documentation first. Not to mention that wamc2017 already provided a solution to your second problem before you even had it.

**Comment by keraldi** [comment]
Also, one issue per issue report. If you have multiple issues, create multiple issue reports. This is to keep track of specific bugs (if you ever happen to find one) and not have cluttered issue tracking. If this were to be a bug (let's say Crack works, Resonance doesn't work) then this issue report would remain open (because Resonance wouldn't work). However, people would then think that Crack also doesn't work, except it works.

That being said, both work. Please close this issue report and save us all time by reading the documentation or watching tutorials first.
