### ISSUE TITLE
[Suggestion][Question][Communtiy Request] Everlating Omega Armor in 1.12.2

### ISSUE THREAD

**Issue by KuBruC** [WayofTime/BloodMagic#1392]
I Recently played the 1.7.10 version, and had very much fun with the Bound and Omega, but I was very annoying to refresh my Earth Omega Armor, so I was missing an Item wich refreches the Timer of the omega Armor using a big Ammound of LP (maybe ~1.000.000) to balance I would Suggest to make the Recipe with a Dragon Egg or an speccial Shard form an Very strong and deathly deamon. Now I am missing the Hole Armor sets. And was struggeling to make an addon by myself (but i failed) so I suggest to Make a "The Old Ways" version -> dierect Port. Also I am Asking the Community for An addon with same effect. I would feel me highly honored if i would a dierect personal Statement, about the creation, the removal of the Bond and Omega and Bound Armor, as well about the Future plans.

 THANKS to anyone who was spendig time to read and reply to my Post.

**Comment by keraldi** [comment]
Because the omega armor was so strong it was never meant to be permanent.
Not to mention that there are other armor systems in place now that can be specialized to be just as strong or stronger in specific fields.
A mod (as is any project or game) is constantly evolving and in this case, the Bound Armor (and with that Omega Armor) has been dropped for a different approach.

Also, a "direct" port is not possible.

Aside from that, a "community request" usually involves a lot of people...

I personally do not miss the Bound Armor as it was too strong/overpowered and well beyond the needs of protection/utility of any modpack. Similarily powerful armor sets from other mods have been nerfed as well as the encounters that might have required them.

The new armor implementations are strong in their own way while maintaining the balance that is required to keep enjoying the survival part of the game.

If you really want a port that has exactly the same functionality, you will have to find someone willing to do it or do it yourself as the plans for this (and almost every other mod) are to progress, not regress or come to stagnation.

Since the mod is licensed under a relativly open license, this is possible without further approval.

**Comment by KuBruC** [comment]
Yeah I under stand, I just thought about to keep up with Quantum Suit or the draconic Armor, and Blood magic was the only magic mod I found made this possible so I still want this addon, probably i'll try to make it on my own and share my results with you.

I always love help.

Thanks for reply.
