### ISSUE TITLE
Demon Crucible

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1480]
#### Issue Description:
How is the second method of usage of the demon crucible supposed to work? I connected a redstone torch to the crucible, and when I put the tartaric gem on it, it's drained instead of being filled with the chunk aura. Am I doing it wrong? 

#### What happens:
crucible drains gem instead of filling it with chunk aura when connected to redstone.

#### What you expected to happen:
To have my gem filled with the chunk aura.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by mywither** [comment]
I believe the Hellfire Forge took over that part of functionality, I could only get redstone control to stop the Crucible from outputting will to the Aura while active. I don't know if it's intentional, or an issue making it not stop outputting will at the same time as it drains will. However, I do know that the powering gem slot of the Hellfire Forge allows you to drain the Will in the Aura into a Tartaric Gem, very similar to how the redstone powered function of the Demon Crucible was described. Until we get an answer or a change making it work like that, just use the Hellfire Forge.
