### ISSUE TITLE
Crash on ticking entity

### ISSUE THREAD

**Issue by rlnt** [WayofTime/BloodMagic#1656]
#### Expected Behavior
Game should continue

#### Actual Behavior
Game crashes

#### Steps to Reproduce
No actual reproduction possible since it crashed after playing for a while

#### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Bloodmagic: 2.4.2-104
Forge: 14.23.5.2847
Multiplayer Server

#### Log
https://pastebin.com/bgJpt66g

**Comment by IronworksProductions** [comment]
I got the same crash fyi

**Comment by Pimeq** [comment]
Same here

**Comment by MissPotato** [comment]
We're getting this crash as well, however, it is happening with vanillia entities, moo fluid, etc. here are some additional crash reports. https://hastebin.com/zewobifize.rb https://hastebin.com/pahikagaxa.rb. The crash only happens when a player loads into the chunks. On our server we ran a /kill @e[type=!player] to kill all entities and that fixed it. It seems to be, even without a well of suffering, keeping track of the entities near it and once that list gets too long the server crashes.

**Comment by hamsterpowerftw** [comment]
Having this crash even when no player has started the mod on the server.
https://pastebin.com/CHu1FhGx

**Comment by TehNut** [comment]
Update
