### ISSUE TITLE
runes are not configured correctly

### ISSUE THREAD

**Issue by TheEvil014** [WayofTime/BloodMagic#1658]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
i can't active the runes

#### What happens:
"you feel these runes are not configured correctly"
![2019-09-29_08 44 35](https://user-images.githubusercontent.com/55938721/65826946-96d42200-e295-11e9-848e-24a246e55494.png)

#### What you expected to happen:
active runes

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 1.12.2
- Forge:

**Comment by keraldi** [comment]
First off, the issue template is not filled out in a satisfactory way. There is a reason why so many questions are asked.

Secondly, this is intended behavior, you might want to check available rituals in the guide book or Ritual Diviner.

Now. Without knowing what ritual you are trying to make (because you haven't told us), I would recommend checking wikis (ritual configurations, as long as they have been ported (which means all rituals from base BM and most from Sanguimancy) are built in the same way).
If you cannot find the ritual you're looking for there, you might want to check with a Ritual Diviner by scrolling through it and looking at a Master Ritual Stone to match shapes.
If you still cannot find it, it's not implemented or doesn't exist at all.
Further questions about how to build a ritual or which one it could be should be directed to the community of the modpack you're using.

Another note: I'm not sure whether you intentionally don't use a Ritual Diviner but it's much easier to build rituals that way since it can automatically place ritual stones for you as well as color them and it also tells you which ritual it's building. Just keep in mind that you should keep an acceptable amount space around the MRS because it won't warn you if it cannot place a block.

**Comment by mywither** [comment]
As Keraldi said, you may simply want to use the Ritual Diviner, it is far easier, and incredibly useful for various reasons.
Another thing, this appears you are trying to create the Ritual of Binding which was phased out in BM2 by the Binding Reagent in an alchemy array creating Binding Arrays for Living Armour and the Bound Tools.
