### ISSUE TITLE
Server crash on chunk unload

### ISSUE THREAD

**Issue by halvors** [WayofTime/BloodMagic#1747]
#### Issue Description:
Server crash on leaving area.

#### What happens:
When the chunk with the altar unloads it causes a server crash.
Crash log: https://pastebin.com/8YRME5ni

#### What you expected to happen:
That the server did not crash.

#### Steps to reproduce:

1. Place altar.
2. Go far away, atleast far enough for the chunk to unload.

Or

1. Place altar.
2. Destroy altar.

____
#### Affected Versions:
- BloodMagic: 3.0.4-9
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by wrincewind** [comment]
I seem to have had a similar issue - i placed down an altar in my creative test world, flew away (several hundred blocks, at least twice my render distance), came back, attempted to break the altar (with an altar in my hand, if that matters), and immediately got a crash-to-desktop.

https://pastebin.com/vn0LMCSZ 

Using Forge 35.1.0 because i haven't updated it in a while, otherwise same versions as above.

**Comment by halvors** [comment]
@wrincewind Indeed, also seems happen when breaking an altar like, my friend experienced that with this very same crash: https://pastebin.com/RnikcVdc

**Comment by WayofTime** [comment]
Am I dumb? I may be dumb.

**Comment by WayofTime** [comment]
Hey look, I'm dumb. Pushing a build now to fix this, look at CurseForge in ~5m.

**Comment by halvors** [comment]
Thx for quick fix :-)
