### ISSUE TITLE
Minor Bug: Witches don't die in well of suffering

### ISSUE THREAD

**Issue by ecatherman** [WayofTime/BloodMagic#1796]
#### Issue Description:
Generated a standard well of suffering ritual beneath a tier 5 altar with a mechanical dirt mob spawner from Industrial Foregoing.

I tried killing them all manually and this happened again within 10 minutes. 

The witches heal themselves faster than the ritual kills them.

#### What happens:
The spawner started spawning mobs as expected and they all took damage from the well of suffering ritual. The witches heal themselves enough that they don't ever die.

#### What you expected to happen:

I expected the witches to last longer than the rest of the mobs but they should die eventually. 

#### Steps to reproduce:

1. build altar with "well of suffering" ritual in a place where witches spawn
2. build mob farm in range of the ritual
3. wait until there are no mobs but witches. (about 5-10 minutes for the foregoing farm)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.0-15
- Minecraft: 1.16

- This is in the direwolf20 pack but I doubt not being in one would effect this.

![2021-03-20_19 03 43](https://user-images.githubusercontent.com/6530707/111887981-0587cc80-89af-11eb-80d6-364aa5a0b16b.png)

**Comment by TehNut** [comment]
Not a bug. Commonly referred to as a "Witch Reactor".

**Comment by wrincewind** [comment]
I think this is intentional - the 'witch reactor' is a known method of generating lots of blood.

If you want to get drops as well as LP, i'd advise using the Industrial Foregoing Mob Grinder (or whatever it's called) to kill the witches when you get too many of them. In my most recent game, I did this using an RSGagues infrared sensor on the front of the grinder, set to turn it on whenever there's more than 16 mobs inside the farm, but you could just as easily set up a timer.
