### ISSUE TITLE
living armor upgrade tomes not combinable

### ISSUE THREAD

**Issue by GreenKnight1315** [WayofTime/BloodMagic#1807]
#### Issue Description:
When adding two upgrade tomes to an anvil, they are not able to be combined.

#### What happens:
I wanted to create a Though II tome out of two level one tomes, but it isn't possible

#### What you expected to happen:
Multiple guides to this mod suggest this should be possible, combining two tomes of the same type.
Has this been removed or not implemented in the 1.16.5 yet, or am i just missing something?

#### Steps to reproduce:

1. get an anvil
2. get two times the same tome
3. try to combine them in the anvil
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.0-15
- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.1.4 (i think)

**Comment by wrincewind** [comment]
Yes, I'm afraid this isn't yet implemented. 

You're really best off using Blood Magic's in-game guide in 1.16, the Sanguine Scientum - it's available if you have the addon mod Patchouli installed, and basically tells you everything you need to know about 1.16 Blood Magic. If it's not in that book, it's not in 1.16.

**Comment by wrincewind** [comment]
We've adjusted how Tomes work in the latest version - you shouldn't need to combine them anymore, as they now apply their XP rather than their level. If you really need to combine a tome, you can add both books to your armour, then use the  "Sound of the Cleansing Soul" ritual to get a single tome with all the XP of both on it.
