### ISSUE TITLE
Crafted Living Armor crashes the game

### ISSUE THREAD

**Issue by M-W-K** [WayofTime/BloodMagic#1873]
#### Issue Description:
If I equip Living Armor that I crafted by hand via progression, it crashes my game. Any attempts to reenter the world crash the game afterward. If I equip living armor that was cheated in via Creative menu, I do not crash.

#### What happens:

Equipping crafted Living Armor causes the game to crash and corrupts the world

#### What you expected to happen:

Equipping Living Armor not to cause the game to crash

#### Steps to reproduce:

1. Craft the pieces of living armor w/ binding reagent
2. Equip, and get crashed
3. If you want to, cheat in living armor instead and equip it to see that it does not cause crashing.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.1.6 - 26
- Minecraft: 1.16.5
- Forge: 36.2.19

**Comment by wrincewind** [comment]
do you have a crashlog for us? This should have been fixed in version 26, so any hints as to what's going wrong would be very helpful.

Also, are you playing a modpack? If so, which one, and what version?

**Comment by M-W-K** [comment]
[crash-2021-12-06_17.00.27-server.txt](https://github.com/WayofTime/BloodMagic/files/7664895/crash-2021-12-06_17.00.27-server.txt)
That should be the crashlog required
I'm using a modpack I assembled myself, if you'd like the modlist i'll write it down.

**Comment by bigenergy** [comment]
I have the same crash

**Comment by rxwsh** [comment]
I had the same crash in my private modpack, testing in a different instance with only Blood Magic, JEI and Controlling(to get the Iron Armour, Ash and Reagent), it didn't cause a crash. I suspected that a performance mod might have caused it and tried Performant which I am using in my normal world and Halogen, which I used before, when the crash happened the first time. Neither replicated the crash. I still can't access my normal world though and the game doens't even show my a crash log.

**Comment by M-W-K** [comment]
Do ya’ll have Twilight Forest in your packs? When I skimmed over the error messages, some of it mentioned a twilight forest changeArmor something.

**Comment by rxwsh** [comment]
Surprisingly I do, I will try to recreate the crash again.

Edit: I just tested it with the following mods and it didn't cause the game to crash either.
![Screenshot 2021-12-09 225044](https://user-images.githubusercontent.com/76978381/145481429-29383760-b2b2-4fd3-9f40-62cc7ae85c6d.png)

**Comment by M-W-K** [comment]
If you’re ok with it, you could send me your modlist and I can compare & contrast with mine.

**Comment by rxwsh** [comment]
This is the list I'm using that caused the second crash, the first time used Halogen instead of Performant, I'm not sure which mod version though.
![Screenshot 2021-12-09 224109](https://user-images.githubusercontent.com/76978381/145482301-21114e89-1c29-467b-b3ac-3cd443daf76f.png)
EnderStorage is disabled as it causes a crash in tandem with Tinkers.

**Comment by M-W-K** [comment]
The major intersections I see are botania and tconstruct

**Comment by 3REBU5** [comment]
Having the same exact bug here on a Valhelsia 3 server. Originally encountered in 3.4.5, was supposedly fixed in 3.4.6, then encountered again in 3.4.7. Including my crash report and server logs if it helps. BloodMagic_Crash.txt is the one from my failed attempt to connect to the server and the other file is the crash from my replication of the bug on a singleplayer creative world.

https://github.com/3REBU5/Blood-Magic-Bugs

**Comment by WayofTime** [comment]
Build is now released, hopefully fixing this crash. It was due to an NPE with the Curios compatibility with the living armour. Thank you for your patience!

https://www.curseforge.com/minecraft/mc-mods/blood-magic/files/3568763
