### ISSUE TITLE
airsigil does not work correctly 1.20.1

### ISSUE THREAD

**Issue by BloodInAs** [WayofTime/BloodMagic#1996]
#### Issue Description:
airsigil does not work correctly 

#### What happens:
sigil work on video

https://youtu.be/Fyu3s4HiH7w

- BloodMagic: 3.3.2-44
- Minecraft:  1.20.1
- Forge: 47.2.1

**Comment by wrincewind** [comment]
how much LP do you have in your network? this looks like the usual behaviour for trying to use the Air Sigil with 0LP.

**Comment by BloodInAs** [comment]
Lp in the network is 5000. It is slowly going away, but there is no flight. Teleportation on the spot.

**Comment by VT-14** [comment]
Your video shows your health being drained when you use the Sigil.  Are the Air Sigil and Divination/Seer's Sigil (to check Soul Network level) bound to the same person/Soul Network?

In dev this only happens when the associated Soul Network is empty so the Sigil takes LP from the player directly.  The current suspicion is that the damage received when using a Sigil with an empty Soul Network seems to be cancelling the momentum the Sigil gives you.  There is a discussion on whether that should be considered intended or not.

**Comment by juzorei** [comment]
Sorry the problem was on our side due to the speed limit
