### ISSUE TITLE
doDayLightCyle false causes Well of Suffering to pause

### ISSUE THREAD

**Issue by Erictch** [WayofTime/BloodMagic#202]
Mods : 
Blood Magics
Extra Utilities
ChickenChunks
Fastcraft
Inventory Tweaks
Ironchests
Not Enough Items
Optifine

Step to produce : 
1) /gamerule doDayLightCycle false
Optional : 
2) /time set 6500(10,20,30,40,50, etc to 90 doesn't work though) to cause a speed up version of WoS

First time reporting an issue as well, so I might have done this wrongly

**Comment by kinnison** [comment]
the WoS ritual relies on the world time advancing, that is true.
It also triggers exactly every 25 ticks so that might explain why you have issues with trying to advance time yourself.  Rather than using world.getWorldTime() it's *possible* that switching to world.getTotalWorldTime() *may* be sufficient to resolve this, but I don't have a system to test on right now.
