### ISSUE TITLE
Bound tools don't respect setHarvestLevel

### ISSUE THREAD

**Issue by bonii-xx** [WayofTime/BloodMagic#252]
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/items/BoundPickaxe.java#L336

Harvest Levels are hardcoded, Iguana Tinker Tweaks kinda needs that. ;)
Didn't look at axe and shovel, but my logs indicate that they don't support it either.

**Comment by Alex-hawks** [comment]
what is the correct way to do that? lookup the tool in the tool registry in forge and return the result?

**Comment by bonii-xx** [comment]
I'm not even sure why it's overloaded, since it seems to do exactly the same as if you'd do a simple setHarvestLevel("pickaxe", 5) in the constructor.

**Comment by nabijaczleweli** [comment]
As far as I can see from that piece of code it makes tools useless if not activated. So it isn't equivalent to simple `setHarvestLevel("pickaxe", 5)`.
If it were to respect `setHarvestLevel()` calls it'd return `super.getHarvestLevel("pickaxe")` instead of `5`, I think.

**Comment by UndeadZeratul** [comment]
Or the pickaxe could set it's harvest level to ("pickaxe", 5) by default, and in the getHarvestLevel method, return (getActivated(stack) && "pickaxe".equals(toolClass)) ? harvestLevel : 0;

That way, you're still checking whether or not the pick is even activated, and if it is, use the harvest level, otherwise it's still 0, same as today.

**Comment by TehNut** [comment]
Solved via #463
