### ISSUE TITLE
Minetweaker loading time

### ISSUE THREAD

**Issue by S60Team** [WayofTime/BloodMagic#267]
Using BloodMagic-1.7.10-1.3.1-3.jar and MineTweaker 3.0.9C
When Using alingside with ModTweaker and MineTweaker it freezes.
After minute Game loading continues.

PS: Here's the Screenshot of my mods: http://i.imgur.com/gy64fpv.png
Here's the Log: https://www.dropbox.com/s/34huo1urub882mz/latest.zip?dl=0
PPS: Can you make a Config Option to disable it?

**Comment by WayofTime** [comment]
It's not freezing, it is loading the compression registry. I have added an output to the log that explains this, for future versions.

If enough people really want, I can add a config option - maybe I can make it work on the server-side only, but it is a necessity for the Sigil of Compression so that it isn't a total lag-fest.

**Comment by S60Team** [comment]
Thank you for your fast response!
Also thanks for the mod ^_^

PS: It's not a bug, i think you should close this issue. Thanks again

**Comment by Neodark7** [comment]
sorry but 3 minutes to load one feature... i can understand it's a necessity but with a huge modpack it's just impossible x)

**Comment by WayofTime** [comment]
Yeah, I think I said somewhere else that the Compression handler is getting tweaked. This issue will be closed as soon as I release it!

**Comment by hilburn** [comment]
@S60Team  - the notification about Minetweaker integration actually occurs after it's been loaded, so yeah, nowt to do with the MT stuff
