### ISSUE TITLE
Ritual of Magnetism not picking up Redstone Ore

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#347]
![2015-06-10_16 53 31](https://cloud.githubusercontent.com/assets/8670392/8087015/d6e36772-0f98-11e5-91f9-f6be38b54444.png)

I have made a contraption that uses Botania's Orechids, Autonomous Activators, Ritual of Magnetism and Ritual of the Crusher to generate Ores and harvest them automatically.
However some of the Redstone Ore is not being picked up by the Ritual of Magnetism. Any other ore that spawned previously to Redstone Ore at the same location was picked up just fine, Redstone Ores that spawn at other location are also picked up.

Forge: 1403
Blood Magic: 1.3.3-4

**Comment by ljfa-ag** [comment]
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/rituals/RitualEffectMagnetic.java#L105:
One item might have more than one possible oredict entries, and this only gets the first one, which doesn't have to be "oreRedstone".

**Comment by Xiaminou** [comment]
I'm not sure about that, it's only on the bottom row that Redstone Ore is not being pulled.

**Comment by ljfa-ag** [comment]
Really? That's weird

**Comment by ljfa-ag** [comment]
Oh I think I know what it is: The Redstone ore glows when you click or step on it.

**Comment by Xiaminou** [comment]
Oh yes, that must be it because the Autonomous Activator would probably right click it at least once, Good call.

**Comment by Xiaminou** [comment]
somehow this bug is back, I decided to play again on my old world today after updating all the mods, and I'm getting the same bug, on the same setup.

**Comment by Blue64** [comment]
Could be error in the block's core data. Did you try tearing it down and building it again using freshly made blocks?

**Comment by Xiaminou** [comment]
I'll give it a shot.

**Comment by Blue64** [comment]
It's usually the problem when people load an old world and a problem "returns", half the time it's actually because the problem is still existing within the already existing blocks, but any new blocks wouldn't have it because they're run through the updated code when they're made, unlike the preexisting ones which were created by the world save data on your hard drive.

**Comment by Xiaminou** [comment]
Well the thing is, it was fixed when I reported it last time, and I remember it working for a while.

**Comment by Blue64** [comment]
So replacing the blocks should fix it, unless the error is deeper than that, which might require a newer world if that's the case, which does suck, but sometimes is unavoidable due to how the game is built. If it still happens in the old world after breaking and replacing the blocks with new ones (sometimes just breaking the block and placing it again isn't enough, AE2 for example refuses to merge stacks of unplaced Interfaces with Interfaces that have been placed and broken, as it's remembering the priority data, which it doesn't get until after it's been placed the first time, but is fixed by crafting it to it's other form then back, because it's "freshly crafted"), if the error still occurs with the new blocks, try it in a new world and see if it still happens (creative should still work for setup, just craft the blocks themselves to be sure).

If it's fixed in the new world, but not in the old, then the problem is local, and MAYBE would be fixed by loading the world minus the mod (Blood Magic in this case), and then saving, quitting, and adding it back in (this will delete any Blood Magic items you have too though, so it'd be last resort)

**Comment by Blue64** [comment]
To be more specific, it'd actually delete all of that mod's objects from the world (ores, altars, items in dungeon chests, etc. Anywhere that has already been loaded once)

**Comment by Xiaminou** [comment]
Tested in a pack with blood magic and TE, confirmed that the bug is back, it doesn't pick up the "sparkling" redstone.

**Comment by Blue64** [comment]
hrm... I shall test this myself as well then, as I also have Blood Magic and Thermal Expansion.

**Comment by Blue64** [comment]
Redstone apparently doesn't light up when it's walked across, this may prove to be a bit more difficult lol time for some cheat-fu ```:P```

**Comment by Blue64** [comment]
well, this is an interesting development! ```minecraft:lit_redstone_ore``` apparently "```doesn't exist```"!
```

[12:15:06] [Client thread/INFO] [inventorytweaks]: codechicken.nei.GuiExtendedCreativeInv
[12:15:06] [Client thread/INFO] [inventorytweaks]: codechicken.nei.ContainerCreativeInv
[12:15:12] [Client thread/INFO]: [CHAT] You are now playing survival
[12:15:25] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:15:47] [Client thread/INFO]: [CHAT] There is no such item with ID minecraft:lit_redstone_ore
[12:15:59] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:16:02] [Client thread/INFO]: [CHAT] There is no such item with ID 74
[12:16:03] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:16:06] [Client thread/INFO]: [CHAT] There is no such item with ID 74
[12:16:17] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[12:16:17] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[12:16:20] [Client thread/INFO]: [CHAT] You are now playing creative+
[12:16:41] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[12:16:41] [Server thread/INFO]: Saving and pausing game...
```
I even tried to copy the block (I remapped it to my Tab Key because I don't have a Mouse Wheel), the lit redstone doesn't copy, but the standard does! this may even potentially be a Forge issue, or worse, a MineCraft issue! (most likely, the wonderful folks at ```Forge Mod Loader``` can fix it though)

**Comment by Blue64** [comment]
reported my findings to forge, linked the issue to here. hopefully more will be revealed.

**Comment by ljfa-ag** [comment]
Lit redstone ore doesn't have an item associated with it, so Item.getItemFromBlock returns null. And that is the problem: seems like I undid the fix with 9ac63779933e84db125e42f7c2d5231ef6e548d6. Whoops...

**Comment by Blue64** [comment]
I'm guessing that Forge would be easily capable of adding that item?

**Comment by ljfa-ag** [comment]
Actually a few blocks have no item since they're not supposed to be placed directly by players.

**Comment by Blue64** [comment]
[you don't say](http://minecraft.gamepedia.com/13w37a)?! ```:P``` I do recall spawning the lit redstone via ```/give``` though, and I've only been playing since 1.7.2, so idk.

**Comment by Blue64** [comment]
apparently, it's possible to fix the lit status via some redstone dust leading to it getting a current (or potentially any redstone related item), so try something like a Lever or something.
