### ISSUE TITLE
Missing config option - potion ID oversight

### ISSUE THREAD

**Issue by Darkos333** [WayofTime/BloodMagic#385]
There is no potion ID setting for Whirlwind(WayofTime.alchemicalWizardry.common.potion.PotionProjectileProtect)

**Comment by Darkos333** [comment]
UPTADE:
Looks like its just the matter of different name: its called ProjProt instead of Whirlwind :/
I dont want to be harsh, but your naming philosophy needs serious revision.
How about thinking twice before you name something, and after you do so - sticking to this name?

**Comment by Arcaratus** [comment]
Way has naming problems (changing named things to something more uniform) and doesn't like it. :P

**Comment by WayofTime** [comment]
Excuse me? I am guessing that you have no experience with mod development or code at all. When someone makes something, they initially give it a pet name to make sure they remember what it does. For instance, ProjProt means Projectile Protection, which is EXACTLY what this thing does. And eventually when you release it in its final form and then want to change the name, you just change the localizations. The name "Whirlwind" only came about after I did a lot of play testing with it, and then settled it as the "upgrade" of the air sigil.

Hell, you can see in the class name that you put down what the name of the actual potion effect would be if you looked. PotionProjectileProtect -> ProjProt. 

Now, I wouldn't be talking like this if you simply told me what the issue was, and then politely mentioned your displeasure. However, you had to phrase it in a manner that made it seem like I was some sort of half-wit simpleton who chooses random names for the hell of it! It is something that I don't really need nor do I deserve.

**Comment by Darkos333** [comment]
Well, looks like you ar not as good at guessing as you believe. While I must admit I never played with mods development, I also have to note that I used to code a lot - and looking at this mess in your code (caused by naming issues) is simply disgusting to me.

If you REALLY need to change the name of given object then you are OBLIGED to replace every single instance of old name with new one. Otherwise you end up having multiple names for the exact same thing - do I really have to explain why this is bad practice? Just because multinaming is solved automatically on code level it doesn't mean you can use it freely on design level without consequences. With this discussion being one of them and probably not the first one - am I right?

If you would like to remember one constructive thing from this conversation, let it be this sentence:
NAMES ARE NOT SUBSTITUTES FOR DOCUMENTATION.
When you need to make some short note of what given object does, then you can simply use comments, they exist for a reason. And obviously this is not the only way to solve your problem, yet all of them being better than multinaming.

As for ProjProt issue, could you please take a look at "potion id" section in the config? Read them aloud. Seriously, do it. Have you noticed some irregularity? Yes, all variables are named after the potions itself, EXCEPT for ProjProt. Intentional or not, this is the result of multinaming. And I managed to quickly solve the issue only because AntiIDConflict mod luckily provides more information than simple ID occupant.

Speaking about naming issues, I have one more thing to say.

This: WayofTime.alchemicalWizardry

So... you decided to name main package after your nickname... while its quite uncommon practice for MC modders, it's not a bad thing itself. However, dont you think it would be better when users remember your nickname because of awesomeness of your mod, instead of simply throwing it at their face? Just saying.

Now for serious things: Can you find the mod name "BloodMagic" somewhere in names of subpackages? No? ME EITHER. When I spotted something fishy in logs regarding your mod for the first time, I was like "WTF is WayofTime? And WTF is alchemicalWizardry? I can't recall installing any of these." I literally ended up pasting package name into google to find out what am I dealing with. Dont you think its exact opposite of correct usecase for such name? You know what is the point of naming things, right? Of course you know, so please make use of this knowledge.
Same thing for config file. "AWWayofTime.cfg" !? Seriously? Bring your "random names" now.

A few final words: dont take me too personal. I have nothing against you as a human, you may be a beautiful person, I even do assume so, since you decided to spare your free time for such project. However I have a few issues with you as a programmer, and I pointed them out. Harsh language is the result of experiencing them and is not intended to insult you in any way.

**Comment by Arcaratus** [comment]
Something called constructive criticism; not an outright rant on what you feel should be.

**Comment by WayofTime** [comment]
There has never been a point when talking to my community where I had to actively take 10 minutes to calm down before I commented and tried to compile a reply. It is not a refreshing experience.

I started working on this mod as a little pet project 2 whole years ago (heck, even longer). It started just as a thing to learn the ropes of modding, try my hand at coding, and see what I could do. That's why I began with "AlchemicalWizardry" as the mod name, and is something I kept in the name.

Now to answer your questions. Why didn't I change the core mod name and its folders? I didn't because by the time I thought to do so the mod became very popular and changing the mod folders would break API support. Why? Because any mod that used the API would have to be forced to update, and would thus not be happy. I'd get so many bug reports it wouldn't be funny.

Why is the config file like that? Because this mod was originally just a side project and I just chose the name of the mod combined with my name. It wasn't for exposure, and like I said before by the time I would have wanted to change it in 1.7.10 it would have broken SOOOOOOO many people's installs. 

"However, dont you think it would be better when users remember your nickname because of awesomeness of your mod, instead of simply throwing it at their face? Just saying." This is answered ONCE AGAIN by how old the mod is.

Frankly, I do not need this attitude in my community. It is toxic, and even though you think it may be, it is not constructive in the slightest. You act as if your opinion is the only valid one and that me even thinking about standing up to your "ideals" is a slight against your very self. If you knew me, you'd understand that I am a very understanding person and welcome almost any idea that someone puts out if they say it with some semblance of humanity. Even those ideas like "hey, Way, why not add this and this even though it completely breaks balance?" I am fine with, because they have an honest opinion. 

However, your delivery of your argument was only the essence of the word: argumentative. If I had to deal with you every single day from day 1 of the mod, the mod would have been perfect grammatically, but would have consisted of only a single class and no content whatsoever. Your attitude drains creativity to such a degree that the mod would have died before I even began.

Have a good day, and I hope the best for you.
-Way

**Comment by OH-Herobrine** [comment]
@Darkos333 Your statement (if you can even class it as a statement) there, is like pelting someone with abuse and ending with 'no offense'. And also, I dont think the issues on Github are for PERSONAL issues with the code itself. Mostly all of the things you complain about are down to the personal preference to WayOfTime, and you just purposely criticized the obvious hard work and time they have put into the brilliant mod. How would you like it if someone came along and told you the project youve worked on for years was 'disgusting' or criticized YOUR naming of the mod. Its a decent mod, and you took the time to use ONE issue you found in the game to verbally abuse WayOfTime's hard work. I find it hard to believe that this was a priority of yours to waste the time it took you to pull issues out of thin air

**Comment by WayofTime** [comment]
@OH-Herobrine Civility isn't some people's strong point. I'd imagine the only reason he felt like this was his ability to hide behind a veil of anonymity.
