### ISSUE TITLE
while true; do documentation  == 0; done

### ISSUE THREAD

**Issue by Nhoya** [WayofTime/BloodMagic#451]
This is a suggestion more then an issue, but really, i think have a better documentation should be a really nice thing because the FTB wiki is REALLY outdated... i'm spending 2 day trying to understand how to use the assassin sigil  without result  and on the wiki the sigil is not mentioned. Isn't  a good thing go and look the source for every single thing, so please do something

**Comment by WayofTime** [comment]
1) There's a reason the Assassin sigil is not mentioned: it is a WIP item. It has no recipe, and the texture that it was given is the water sigil - that alone should raise alarm bells telling you that something isn't right.

2) Also, there IS documentation. It says so right on the main post of the mod. Download Guide-API, craft a mail-order catalogue, and drop it on the ground. I spent too much work on those for someone to tell me "so please do something."

3) That code fragment is wrong. Should be: do{//Put code here to insert documentation}while(documentation == 0). Even this would be a problem, since the do while loop always does at least one iteration - I already have the documentation, so it would cause duplicate copies.

If you are going to accuse me of something, please look for it.

**Comment by Nhoya** [comment]
I'm not accousing you, it was just my point of view, i can undersand the quantity of work under this mod but for me the  problem was just find something more accurate, btw i read all the sanguine scentiem yet. I'm sorry if you think i'm accusing you

**Comment by WayofTime** [comment]
So you already knew of the book? The writing style is supposed to give you some of the details, but not all of the specifics.

**Comment by Nhoya** [comment]
ofc i know and i think is a really nice idea explain all as a story
