### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [WayofTime/BloodMagic#507]
I get the Following crash using HQM Book and try to looking for a recipe in NEI.
Not sure if theis is a Blood Magic(Line 10,12,13,14)

Test case:
Join a game.
Don't open NEI inventory.
Open any quest in the HQM Quest book.
Try to open any recipe the HQM Quest book. with R button (this should trigger NEI opening).
Game will crash.

https://gist.github.com/Dream-Master/25b4041c4885fde37d8f#file-nei

http://openeye.openmods.info/crashes/9a8f82d382cb416f77ca038e853cfbac

**Comment by Dream-Master** [comment]
Any news here?

**Comment by Blue64** [comment]
I would like to point out a few problems with this crash:
* Optifine is installed
  * not supported by 2 of your other mods
  * Closed Source Mod
* it's a kCauldron Server
  * a lot of mods are shying away (or fleeing) support for kCauldron Servers because they change some behavior in the way MineCraft actually runs (I don't recall what specifically it changes)

Have you been able to reproduce this in Single Player, or only on the Server? If it's only on the Server, you'd need to contact the kCauldron people about it.

I see you also mentioned it to NEI (with zero response as of yet from them also). AFSU mod ruled out my assumption that it may have been directly caused by NEI, as AFSU comes before AWWayofTime alphabetically (which prefixes most Blood Magic entries), so it does indeed *appear* to be caused by Blood Magic, but if it's exclusive to the Server, then it's most likely kCauldron causing it.

**Comment by Blue64** [comment]
so...all fingers point here. did you ever manage to reproduce it in single player?

**Comment by Dream-Master** [comment]
Yes crash in single player too.

**Comment by Blue64** [comment]
well, that rules out kCauldron being the problem then lol

**Comment by Dream-Master** [comment]
thats true

**Comment by Blue64** [comment]
@TehNut any ideas?

**Comment by TehNut** [comment]
No. It hasn't been reported by any other pack using HQM and BM. I assume it's something in your specific instance.

**Comment by Blue64** [comment]
so, Binary elimination basically huh? (figure it out, 50% at a time, just keep the half that crashes until it becomes a really tiny list, or just launch it minus a mod, if no crash, keep that mod in and keep looking for other mods that don't crash). I'm assuming it's a 3-way incompatibility.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Comment by Dream-Master** [comment]
We can't test this in 1.8 because most mods like HQM not available for this version.
