### ISSUE TITLE
[1.8] Bound tools issues

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#543]
BloodMagic-1.8.9-2.0.0-43-ss
Bound tools doesn't consume LP 
Bound shovel mines dirt under the user.
Bound tools fire even if charging indicator is not full (but must be over 50 %) - it does mine smaller area, but I'd argue this not very user-friendly way of choosing area of operation.

**Comment by WayofTime** [comment]
I've added the LP cost and made it translated properly. I'll keep this up for the last issue, though, since I agree with the enhancement.

**Comment by Arcaratus** [comment]
Any bound tool suggestions shoot at me! I'm up for any pointers on how the charging effect should work and such.

**Comment by Kytte84** [comment]
For some reason whenever I use a bound tools ability it crashes the server. Any suggestions?

**Comment by WayofTime** [comment]
We need a crash log.

**Comment by Kytte84** [comment]
This is the error msg the server spits out, but it doesn't crash. Just ejects the player from the server.

9:22:03 PM [Server thread/FATAL]: Error executing task
9:22:03 PM java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Ticking player
9:22:03 PM at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_73]
9:22:03 PM at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_73]
9:22:03 PM at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
9:22:03 PM at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
9:22:03 PM at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
9:22:03 PM at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
9:22:03 PM at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
9:22:03 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
9:22:03 PM Caused by: net.minecraft.util.ReportedException: Ticking player
9:22:03 PM at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:379) ~[lf.class:?]
9:22:03 PM at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:326) ~[lm.class:?]
9:22:03 PM at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:126) ~[ip.class:?]
9:22:03 PM at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[ip.class:?]
9:22:04 PM at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
9:22:04 PM at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_73]
9:22:04 PM at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_73]
9:22:04 PM at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
9:22:04 PM ... 5 more
9:22:04 PM Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_71057_bx()I
9:22:04 PM at WayofTime.bloodmagic.item.ItemBoundTool.func_77663_a(ItemBoundTool.java:82) ~[ItemBound

**Comment by TehNut** [comment]
First off, use pastebin. Second, that doesn't look like the full stacktrace.
