### ISSUE TITLE
Problem: seems like a world gen conflict

### ISSUE THREAD

**Issue by lightning02** [WayofTime/BloodMagic#544]
Hello, I found this problem adding blood magic, seems like a world gen conflict that spam in the console and make the game a bit laggy, is this a problem of blood magic (alchemicalwizardryBooks) or remain in motion (PlanetGuy Lib)?
How should I proceed?

The latest log is: http://pastebin.com/AvvWbyKB
The fml-client-latest.log is: https://copy.com/lIJMB7KzBfQutl2R/fml-client-latest.log?download=1 (It was a bit too long for pastebin)

**Comment by TehNut** [comment]
I don't see any spam in either of those logs that are related to either mentioned mods.

**Comment by Blue64** [comment]
Pastebin Lines 4-16 for example, I believe it's more of a resource pack issue 
```
[17:55:19] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Alexander\AppData\Roaming\.technic\modpacks\wonderful-bounty-ultra-pack\mods\BloodMagic-1.7.10-1.3.3-17.jar
```
Note the ```.technic\modpacks\wonderful-bounty-ultra-pack\``` part of the error, does this mod, or yourself, use any non default resource packs? That could cause spam like this.

I would also track down the source of this error:
```
[18:07:53] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft:matmos_hl.water.lake
```
Since I'm guessing it's not supposed to be missing, and report it to the appropriate mod author, either that or you've got data corruption going on, which is easily fixed by simply reinstalling the corrupted portion.

**Comment by lightning02** [comment]
the hard works is individuate the corrupted portion :/
i'll try to turn this thread to Matmos.. hope to solve.
anywya thanks for the response :)
