### ISSUE TITLE
Misaligned text in the Sanguine Scientiem

### ISSUE THREAD

**Issue by stephanstross** [WayofTime/BloodMagic#549]
This error occurs in the version of Blood Magic in the latest version of The Breakfast Special modpack, on the ATLauncher. The text of the sanguine scientiem is not correctly aligned on the page, and the bottom half of most pages of text comes off the page, making the book pretty much unreadable. I've attached a screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/1668360/12155877/b59c08d8-b495-11e5-9207-c08eea613191.png)

EDIT: cross-posted to the Breakfast Special github: https://github.com/BreakfastCraft/BreakfastSpecial/issues/18

**Comment by TehNut** [comment]
What version of GuideAPI

**Comment by Blue64** [comment]
I too have this issue, up to date as of last week I believe in version 1.7.10. The text is all there, it's just, well, yeah. Makes it kinda difficult to read when you're trying to figure out if you're reading words or a GUI lol
```
Guide-API-1.7.10-1.0.1-23.jar
BloodMagic-1.7.10-1.3.3-17.jar
Java 8
Windows 7, 64 Bit
```
I'm not sure why it deems the center of the GUI as a good starting point. Also, I notice some pages are rather long (one or two pages I couldn't finish reading because it still went off my screen), if the text isn't supposed to resize, might I recommend spreading it out over more pages instead? 75% of the current page length should fit no problem from what I've seen.

**Comment by TehNut** [comment]
I rewrote a few pages in GuideAPI which included changing formatting. Downgrade to the second most recent stable build. (I think it's 20?)

**Comment by Blue64** [comment]
It is 20.
[**_CurseForge Link**_](http://minecraft.curseforge.com/projects/guide-api/files/2241379)
[**_CurseForge Direct Download Link**_](http://minecraft.curseforge.com/projects/guide-api/files/2241379/download)
(both MineCraft 1.7.10)

**Comment by TehNut** [comment]
Anyways, not a BM issue.

**Comment by Blue64** [comment]
It wasn't directly, but was compatibility-wise, since the Sanguine Sanctum is a BM item `:P`

**Comment by TehNut** [comment]
No, the Sanguine Sanctum is a GuideAPI item. This is 100% not BM.
