### ISSUE TITLE
A player just 'tested' something on me and another player, and we're unable to login

### ISSUE THREAD

**Issue by ajthemacboy** [WayofTime/BloodMagic#575]
Here is the crash report: https://gist.github.com/ajthemacboy/9fe6dd219ce9a6c5f646

I have no idea what was 'tested', as the (I can only assume) troll just logged out and is not making contact. I'm sorry I can't be more specific.

Now, when me and the other player login, we immediately crash.

**Comment by Blue64** [comment]
My guess:

```
-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
    Entity ID: 297256
    Entity Name: ajthemacboy
    Entity's Exact location: 632.38, 53.52, 335.75
    Entity's Block location: World: (632,53,335), Chunk: (at 8,3,15 in 39,20; contains blocks 624,0,320 to 639,255,335), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Entity's Momentum: 0.03, 0.00, 0.06
```

Somebody forgot to check if a Player was Null before posting that section of Code. Null is usually a bad thing I've noticed lol

Edit: merged posts.

```
    Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
```

Worth noting: KCauldron sometimes causes problems because ~~it's~~`it changes default values in MineCraft. OptiFine on the other hand is` Closed Source (so nobody knows what to not put to avoid breaking it, or what to put to fix the break, except the Author of the Closed Source Code), and thus some Mod Devs don't provide support for it.

Edit: information corrections.

Edit: Merged Posts.
If I'm not mistaken, you've got the wrong Blood Mod for your crash report, that log says BloodArsenal, this is BloodMagic, which that mod is an Add-on to.

**Comment by Blue64** [comment]
```
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
```
Worth noting: KCauldron sometimes causes problems because it's Closed Source (so nobody knows what to not put to avoid breaking it, or what to put to fix the break, except the Author of the Closed Source Code), and thus some Mod Devs don't provide support for it.

**Comment by Blue64** [comment]
OptiFine is the same way.

**Comment by Blue64** [comment]
If I'm not mistaken, you've got the wrong Blood Mod for your crash report, that log says BloodArsenal, this is BloodMagic, which that mod is an Add-on to.

**Comment by Arcaratus** [comment]
Aye, you are using an outdated version of Blood Arsenal, update it to the latest and someone close this

**Comment by Blue64** [comment]
Right team of people at least lol here is the correct issue tracker for you By The Way: [**_LINK**_](https://github.com/Arcaratus/BloodArsenal/issues)

Edit: didn't see Arcaratus post just before me lol
