### ISSUE TITLE
[1.8] Thorns Enchant causes Sentient and Living Armour to take damage

### ISSUE THREAD

**Issue by Pitfallingpat** [WayofTime/BloodMagic#604]
Version 1.8.9-2.0.0.0-15
Same as title, having the thorns enchantment on either chest armours is causing them to take durability damage when you get hit (and thorns does damage back?). The rest of the set is unbreakable as far as I can tell, but thorns is causing problems, and the chest piece is where all the set upgrades is saved for the Living Armour.

**Comment by TehNut** [comment]
Oh boy. This actually seems like an oversight in Forge.

`EnchantmentThorns` is calling `ItemStack#damageItem(int, EntityLivingBase);` instead of checking instanceof `ISpecialArmor` and then calling  `ISpecialArmor#damageArmor(EntityLivingBase, ItemStack, DamageSource, int, int)`. Simple enough fix for Forge.

**Comment by TehNut** [comment]
Oh hey Forge fixed this apparently https://github.com/MinecraftForge/MinecraftForge/commit/5d2b8438c9953502a7ecc51d9f7f1f8552cbb7ae
