### ISSUE TITLE
Routing nodes not behaving as expected 1.8.9

### ISSUE THREAD

**Issue by Periphera** [WayofTime/BloodMagic#661]
Blood Magic  1.8.9-2.0.0.19

Made a set-up to automate input/output of stone and slates in the blood altar. I'll try and illustrate the set-up:

South^

Master Node

(2 )               (1)
ALTAR (3) Chest
- After posting this issue, the above illustration slightly off-sets, but hopefully it makes sense from the description below.
  I'm using one chest for the stone and slates. All 3 nodes connected to master node. The nodes are configured as follows:

(1) - Input Routing node: No configuration. Adjacent to Chest @North
(2) - Input Routing node: North - Precise filter - Blank slate - set to 'Everything'. Adjacent to altar@North
(3) - Output Routing node: West - Precise filter - Blank slate - set to 'Everything'
                                           East - Precise filter - Stone - Ghost Item Amount:1
                                           In between Altar and Chest

Tier 3 altar. Capacity 34k. Alter filled.

What i expect - With 34k Lp, 34 Stone should be infused into 34 Blank Slates.

What actually happens - The system stops after making 8 slates. Have to remove those slates for the system to continue. Even if I set the blank slate ghost item amount to 34 in the output routing node, the system sill halts after making 8 slates.

Is this a bug or are my node configurations wrong?

(same thing happened when i re-placed the nodes and switched to making reinforced plates from blank plates. stops after 8 reinforced slates are in the chest)

Also, the altar is drained of any blood when runes are upgraded from blank runes. Is this an intended feature?

**Comment by WayofTime** [comment]
I can only comment on the latter issue right now. If you break a rune on the layer that has capacity runes, it will reset to the default max capacity - this is the correct behaviour.

Other than that, it is hard to troubleshoot your issue in plain text - you may have a loop, since your node (1) has no filter at all. The node system transfers a max of 8 at a time, so I think the slates from your chest are going back into the chest. Try changing the priority of your nodes - 0 is first served, and 9 is last served.

**Comment by Periphera** [comment]
Yup, as suspected it was my oversight not putting a filter on that node.
Works fine now. Thanks.
