### ISSUE TITLE
Crash while launching game. (1.9)

### ISSUE THREAD

**Issue by AxolotlAccount** [WayofTime/BloodMagic#683]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens: While loading, the game crashed with this crash report:

http://pastebin.com/hkXCApgc
#### Steps to reproduce:
1. I pressed ''play''
2. Game started loading.
3. Crash happened.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9- 2.0.0-21
- Minecraft: 1.9
- Forge: 1.9-12.16.0.1782-1.9

**Comment by WayofTime** [comment]
This is most likely due to Forge being in a constant state of flux, changing and adding classes. This build was compiled against the one before 1770, so we'll have it fixed tonight by updating our forge. Probably will have a release tonight with minor bug fixes, but it is still largely unplayable :D
