### ISSUE TITLE
Tome of Peritia (Broken)

### ISSUE THREAD

**Issue by Bellwar** [WayofTime/BloodMagic#774]
#### Issue Description:

Basically, it eats up all your XP and broke your XP status (or how to call it)
#### What happens:

You can store XP there normally and get it back until you save there all your XP your bar get stuck and you can get any XP or levels only through commands
- You can't get it working again, even restarting MC your XP bar is stuck.
#### What you expected to happen:

Save and load XP from it and be able after using obtain more XP in a game.
#### Steps to reproduce:
1. Get the Tome
2. Store all your XP
3. Go kill mobs (no XP)
4. Go get back your XP from the Tome (all is gone)
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-38
- Minecraft: 1.9
- Forge: 12.16.1.1907

**Comment by Bellwar** [comment]
Update: You have to put the Tome away after storing the XP in it. And then you can't get any of it again.

**Comment by WayofTime** [comment]
This seems to be one of those impossible to reproduce bugs... It's working on my end but I know tlovetech had this issue too. Does it happen in 1.9.4 for you or anyone?

**Comment by ArcheKnight** [comment]
It just happened to me in 1.9.4. I'm a very sad panda. I'm on a server with relatively few mods (about 59, I believe) and it happened as described. I stored a bunch of experience (it was automatically taking the exp even) and I can't remember if I lost all exp before or after storing the book but now I can't get exp on character or in the book.

**Comment by WayofTime** [comment]
So you can't get any exp on your character now even if you don't have the book on you?

**Comment by ArcheKnight** [comment]
That is correct. Excepting the use of commands I cannot get any experience and the book is now empty. I probably should have mentioned earlier that I'm using 1.9.4-2.0.1-40.

**Comment by WayofTime** [comment]
The fact that you get no experience whatsoever is weird. Even using a couple stacks of bottles o' enchanting doesn't fix it, eh?

EDIT: @ArcheKnight if it is still happening can you get your server owner to send me your player.dat file? I need to look at it to see what is making your character glitched.

**Comment by WayofTime** [comment]
So your's was on a server... Were you on a server @Bellwar ?

**Comment by TehNut** [comment]
I'm fairly sure this issue is caused when a player has negative experience.

**Comment by WayofTime** [comment]
Didn't know the tome would give bad experiences...

**Comment by Melakion** [comment]
Happened to me too, on server.

**Comment by WayofTime** [comment]
If anyone can provide me a .dat of their character, that would be great! ^_^

**Comment by ArcheKnight** [comment]
I'll try to get that file when my server admin is available.

**Comment by TehNut** [comment]
`/xp PLAYERNAME 1L` _should_ theoretically fix this issue, by the way. Worth a shot instead of deleting player files.

**Comment by Melakion** [comment]
admin had to set me to 0, then could add levels, adding levels directly didnt work.

**Comment by syntax-error** [comment]
I've also been experiencing this issue. I've uploaded my [single player data](https://db.tt/YaT5AL0R) to dropbox to assist with debugging.

My history with this bug:
- Shift-right clicked the tome, all 27 of my levels were placed directly into the book in one hit.
- I placed the tome in a chest.
- I continued to play my game, before realising I was not accruing XP any more.
- Being uncertain, returned the tome to my inventory. I was puzzled because I was not gaining XP, and the tome had not gained it either.
- Whilst in my inventory, the tome does accrue my XP normally.
- I right click the tome, it empties fully in one click, but does not restore any XP.
- I still cannot accrue XP.
- Added levels using "/xp 27L", which results in me gaining the required XP directly, regardless of the tome being in my inventory. However, I still could not accrue XP normally.
- I uploaded my player dat file
- I double checked the "/xp 1L" advice, it produces identical results as before.
- I delete the tome and try the command again. Identical results.
- At the time I had 29L of xp accrued exactly (thanks to commands)
- I use "/xp -29L" to reduce my level to 0. Still Identical results as before.
- I repeat the command. My level and XP are now thoroughly 0, or so I presume.
- I can now accrue XP normally.
- I cheat in a new tome. It now stores and returns my xp in 1 level jumps per click, instead of all of it.
- The tome accrues XP whilst in my inventory. When it is outside of my inventory, I gain XP as expected.

I hope my account can provide some enlightenment on this bug. Do note that my provided player dat file is from before I returned to normal, so should be relevant for debugging purposes.

**Comment by Bellwar** [comment]
I was on singleplayer when it happened to me, sadly I wasn't able to come here and then I lost my world so no I can't give you the player.dat, wish I could be here before and read it.
But didn't try to get my XP to 0 with commands only with tome which doesn't fix anything. So I think it can be repaired by getting to compleat bottom.

One more time sorry for late respond. BTW I would say, the tome should get whole overwrite or part of it.

**Comment by TehNut** [comment]
@syntax-error Just took a look at your data file.

![wut](http://i.imgur.com/SIVOpCq.png)

I think it's safe to say that _something_ is definitely very, very wrong...

Edit: Here is what a player with 0 experience is supposed to look like

![okay](http://i.imgur.com/VmRmk5X.png)

**Comment by WayofTime** [comment]
Must be because of the 666 in the XpSeed.
https://github.com/WayofTime/BloodMagic/commit/d1bdec7113ba593f1240e0deb658078d4a771db4

**Comment by syntax-error** [comment]
Sorry to be the bearer of bad news, but, I've updated to 2.0.1-43, and I can't refund more than just shy of 18 levels out of the tome. You can find my [current player dat file here](https://dl.dropboxusercontent.com/u/28830608/efa2865d-05fc-4cd8-96fd-fa3126e9242b.dat).

Salient facts:
- I have done some enchanting and anvil-ing since the update
- I have tried the /xp -1L trick. No change in this new bug.
- The tome works fine until you reach around 16 levels, at which point it only grabs a percentage of the XP needed to go to 17, then goes to half way through 17, then fills the bar, but doesn't go to 18.

Tangentially related: does the tome interfere with gaining the Experienced living armor trait? I've been wearing a training bracelet for it, and have gained enough experience to go from around level 30 to level 33, but no trait. Was just wondering whether the tome was catching the experience in a way that meant that the trait tracker never fires.

**Comment by WayofTime** [comment]
Ok, thanks! Fixed both of them in that. Man, this was an annoying bug.

You at least are able to gain exp it seems.
