### ISSUE TITLE
Ethereal Mimic blocks mimic wrong wood.

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#965]
#### Issue Description:

When an ethereal mimic block is given spruce wood, it imitates oak wood.

#### Steps to reproduce:

ETA:  It may be relevant that I've previously used Lighted Mimic Blocks with an oak-wood "cover".
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-65.jar  (ETA, oops)
- Minecraft: 1.10.2
- Forge:  2099

**Comment by TehNut** [comment]
That is not a Blood Magic version.

Does this happen with any meta blocks?

**Comment by MentalMouse** [comment]
Sorry, fixed the version.  I'm not sure what you mean by "meta blocks".

**Comment by TehNut** [comment]
Blocks with metadata.

**Comment by MentalMouse** [comment]
I discovered wool always shows white, and a Bo'P wood shows as a different Bo'P wood.  However, Waila reports the correct "cover" block.

**Comment by MrNinja93** [comment]
I can confirm this with all metadata blocks and mimics, noticed it before but assumed it was a limitation/what was meant in the book by "default" state with stairs (or however it's written), only happens if you place the mimic down then place the block into it. Placing mimic onto block works perfectly though.

Edit: Screenshots for reference, 
Left -  mimic is placed onto block
Right- block is placed into mimic

![2016-11-12_00 34 14](https://cloud.githubusercontent.com/assets/21979276/20234171/d9dcea9a-a86f-11e6-94f9-b398c7ad3ad2.png)
![2016-11-12_00 34 16](https://cloud.githubusercontent.com/assets/21979276/20234172/d9dfd174-a86f-11e6-9059-b270f46ad88a.png)

**Comment by MentalMouse** [comment]
Edit:  @MrNinja93:  Thanks for pointing out the workaround... which unfortunately doesn't seem to work for me.  Right-clicking with the mimic blocks simply places them.
