### ISSUE TITLE
[1.10.2] Fruit in the altar crash

### ISSUE THREAD

**Issue by jawsawn** [WayofTime/BloodMagic#968]
#### Issue Description:
Adding Harvestcraft cranberry in the altar crashed the client.
Crash Report: 
https://gist.github.com/JAWSAWN/43ad769eb3c9ac3368ebb1ef61f8f9c1

#### What happens:
I added a Crafting Harmonics recipe to altar, doesn't end up working, so I put a berry in the altar and it crashed me to desktop.

#### What you expected to happen:
Berry to stay in the altar, doing nothing.

#### Steps to reproduce:

1. right click the altar with a harvestcraft fruit
2. boom
3. ???
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 0-66
- Minecraft: 1.10.2
- Forge: .2122

**Comment by Arcaratus** [comment]
Those are not "full" Blood Magic or Forge versions, but they will suffice. Just make sure to put the full version next time.

This problem is also on Crafting Harmonic's side as they are tinkering around with adding Altar Recipes in their own manner, report the crash to them.

EDIT: Upon seeing the Crafting Harmonic's page, the author has stated that updating the mod will be pretty unlikely. I suggest you install another recipe adder mod instead such as CraftTweaker and ModTweaker

**Comment by jawsawn** [comment]
Is the crash caused by crafting harmonics?

I know I put the last digits of the versions since im using the ""latest"" ones :)

**Comment by Arcaratus** [comment]
Yes the crash is caused by Crafting Harmonics.
